services:
  redis:
    image: redis
    ports:
      - 6379:6379
  worker:
    build: .
    environment:
      REDIS_HOST: redis
    command: celery -A imgnet.worker.celery worker -P solo -l DEBUG
    depends_on:
      - redis
    volumes:
      - /tmp:/tmp
  flower:
    image: mher/flower
    ports:
      - 5555:5555
    command: celery --broker=redis://redis:6379 flower -l DEBUG
    depends_on:
      - redis
  imgnet:
    build: .
    command: uvicorn --reload --host 0.0.0.0 "imgnet.main:app"
    environment:
      REDIS_HOST: redis
    ports:
      - 8000:8000
    depends_on:
      - redis
      - worker
    volumes:
      - /tmp:/tmp
